# Installing the necessities to DB
---
# hosts
- hosts: db
  gather_facts: yes
  become: true


  tasks:
  - name: Installing mongod in db machine
    apt: pkg=mongodb state=present
  - name: Cloning GIT
    git:
      repo: https://github.com/jo763/Shahrukh_eng99_CICD
      dest: /home/vagrant/repo
      clone: yes
      update: yes
  - name: Deleting and replacing mongod.conf file
    shell: |
      cd /etc
      rm mongodb.conf
      cp /home/vagrant/repo/environment/db/mongod.conf /etc/mongodb.conf
      systemctl restart mongodb
      systemctl enable mongodb
    become_user: root
